version: '3.7'

services:
  postgres:
    container_name: postgres_container
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: postgres
      PGUSER: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
